### ISSUE TITLE
error when running shadow generate

### ISSUE THREAD

**Issue by kotaxyz** [tori29umai0123/ShadowGenerator#2]
hi there thanks alot for developing this awesome tool , i was trying to test it but i get error every time i click shadow generate , i use the same model and controlnet , emmbeding as provided in the config.yaml file and didn't change anything , the mask generation and auto tagging works fine , the only issue is the last step which is shadow generate 

here is the log 

* Serving Flask app 'web_server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [05/Jul/2023 12:58:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Jul/2023 12:58:45] "POST /generate_mask HTTP/1.1" 200 -
using existing wd14 tagger model
2023-07-05 12:58:48.793644: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2023-07-05 12:58:48.793823: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-07-05 12:58:48.811266: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
127.0.0.1 - - [05/Jul/2023 12:59:26] "POST /parse_prompt HTTP/1.1" 200 -
[2023-07-05 12:59:36,840] ERROR in app: Exception on /generate_shadow [POST]
Traceback (most recent call last):
  File "I:\shadow-gen\ShadowGenerator\env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "I:\shadow-gen\ShadowGenerator\env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "I:\shadow-gen\ShadowGenerator\env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "I:\shadow-gen\ShadowGenerator\env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "I:\shadow-gen\ShadowGenerator\web_server.py", line 42, in generate_shadow
    out_path = ShadowGenerator.main(max_size, output_dir, image_path, mask_path, prompt)
  File "I:\shadow-gen\ShadowGenerator\ShadowGenerator.py", line 95, in main
    out_path = Shadow_Generator.generate_Shadow(max_size,output_dir,image_path,mask_path,prompt)
  File "I:\shadow-gen\ShadowGenerator\ShadowGenerator.py", line 24, in generate_Shadow
    h, w, _ = init_img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
127.0.0.1 - - [05/Jul/2023 12:59:36] "POST /generate_shadow HTTP/1.1" 500 -

**Comment by RyanzW0521** [comment]
try to change line 20 into `init_img = imread.imread(image_path,1)`

**Comment by kotaxyz** [comment]
it worked thanks mate

**Comment by RyanzW0521** [comment]
您的邮件我已收到，辛苦！
